development: &development
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hoge_development
  pool: 5
  username: root
  password:
  host: localhost

test: 
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hoge_test
  pool: 5
  username: root
  password:
  host: localhost
